# Generated by Django 3.1.8 on 2021-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("delivery_id", models.CharField(max_length=100, unique=True)),
                ("order_id", models.IntegerField()),
                ("vendor_id", models.IntegerField()),
                ("label_url", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN_ERROR", "Error desconegut"),
                            ("ERROR_FROM_BODY", "Error alta enviament"),
                            ("LABEL_SENT", "Etiqueta enviada al venedor"),
                        ],
                        max_length=20,
                        verbose_name="Estat de l'enviament",
                    ),
                ),
            ],
        ),
    ]
