# Generated by Django 3.1.8 on 2021-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="delivery_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ERROR_FROM_BODY", "Error alta enviament"),
                    ("LABEL_SENT", "Etiqueta enviada al venedor"),
                ],
                max_length=20,
                verbose_name="Estat de l'enviament",
            ),
        ),
    ]
