# Generated by Django 3.1.8 on 2021-07-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210716_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=100, verbose_name="Id de l'enviament"),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='label_url',
            field=models.CharField(blank=True, max_length=200, verbose_name="Url de l'etiqueta"),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order_id',
            field=models.IntegerField(verbose_name='Id de la comanda de WooCommerce'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vendor_id',
            field=models.IntegerField(verbose_name='Id del vendor de WooCommerce'),
        ),
    ]
