# Generated by Django 3.1.12 on 2021-07-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shipment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_message',
            field=models.CharField(blank=True, max_length=100, verbose_name='Missatge de seguiment'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Notes de seguiment '),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_status_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data de creació del darrer estat de l'enviament"),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualització seguiment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('ERROR_FROM_BODY', 'Error alta enviament'), ('LABEL_SENT', 'Etiqueta enviada al venedor'), ('IN_PROCESS', 'En proces'), ('ON_HOLD', "Particularitat al proces d'enviament"), ('ERROR_FROM_TRACKING', 'Error API de seguiment'), ('DELIVERED', 'Entregat')], max_length=20, verbose_name="Estat de l'enviament"),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualització creació'),
        ),
    ]
