version: "3.7"

services:
  develop_lazona_conn_app:
    container_name: develop_lazona_conn_app
    image: registry.digitalocean.com/codihub/lazona_connector:release-22.12.001
    command: gunicorn lazona_connector.wsgi:application --bind 0.0.0.0:8000 --reload --threads=10
    env_file:
      - ./settings/preproduction.env
    ports:
      - "80:8000"
    depends_on:
      - develop_lazona_conn_db

  develop_lazona_conn_celery:
    container_name: develop_lazona_conn_celery
    image: registry.digitalocean.com/codihub/lazona_connector:release-22.12.001
    command: celery -A api.tasks worker --beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./settings/preproduction.env
    depends_on:
      - develop_lazona_conn_db
      - develop_lazona_conn_redis

  develop_lazona_conn_db:
    container_name: develop_lazona_conn_db
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  develop_lazona_conn_redis:
    container_name: develop_lazona_conn_redis
    image: redis
