name: Build

on: [workflow_dispatch, push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: 'secret_key'

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and coverage
        run: coverage run --source='.' manage.py test

      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
